### ISSUE TITLE
ca_cert test in gocli branch has not effect

### ISSUE THREAD

**Issue by Kiemes** [cloudfoundry/bosh-acceptance-tests#30]
https://github.com/cloudfoundry/bosh-acceptance-tests/blob/gocli-bats/spec/bat/bosh_runner_spec.rb#L34

The test is green with or without `let(:ca_cert)` statement.

Is this a leftover from ruby cli times?

**Comment by dpb587-pivotal** [comment]
Looks like a leftover and forgotten test from when we were removing those args in the test in favor of environment variables. Feel free to remove if you beat us to it :)

**Comment by Kiemes** [comment]
Before I do remove the test, is there any place else where you are testing the director ca cert being passed to the bosh cli command? I did not find any.

If I get it right, the BATS will fail if you run them and have not specified the correct env vars, i.e. BOSH_CLIENT_SECRET or BOSH_CA_CERT in the pipeline container?

**Comment by dpb587-pivotal** [comment]
Right, it's acceptable for BATS to fail if the caller did not correctly configure the client auth / CA cert, if necessary. Same sort of expected failure as if director IP was misconfigured.

**Comment by Kiemes** [comment]
Ok, I will create two PRs. One to remove the unnecessary test from bats repo. The other one on https://github.com/cloudfoundry/bosh/blob/master/docs/running_tests.md#bosh-acceptance-tests-bats as the required env vars for running BATS should be mentioned in the documentation on how to run BATS. Something similar as used for BRATS.

**Comment by Kiemes** [comment]
New documentation for running BATS with BOSH CLI v2 https://github.com/cloudfoundry/bosh-acceptance-tests/commit/418d12e01c476c253a067042edb2c3c6880f52df
